import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/session-provider";
import { Menu } from "./music/components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  // console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}  suppressHydrationWarning={true}>
        <SessionProvider session={session}>
          {session ? <Menu /> : null}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
