import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/session-provider";
import { Menu } from "../components/menu";
import { Sidebar } from "./music/components/sidebar";
import { playlists } from "./music/data/playlists";
import { ScrollArea } from "@/components/ui/scroll-area";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ height: "100%" }}
        suppressHydrationWarning={true}
      >
        <SessionProvider session={session}>
          {session ? (
            <div>
              <Menu />
              <div className="grid grid-cols-7 mt-14 relative">
                <aside className="self-start sticky top-0 col-span-1 ">
                  <Sidebar playlists={playlists} className="hidden lg:block" />
                </aside>
                <main className="col-span-6">
                  <ScrollArea className="h-[calc(100vh-56px)]">{children}</ScrollArea>
                </main>
              </div>
            </div>
          ) : (
            <>{children}</>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
